name: jd_youtobe_api_plugin
description: A new Flutter plugin.
version: 0.0.1
author: Lijinjinjin
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.wafbbail.jd_youtobe_api_plugin
        pluginClass: JdYoutobeApiPlugin
      ios:
        pluginClass: JdYoutobeApiPlugin
